### ISSUE TITLE
Stale notifications

### ISSUE THREAD

**Issue by rnicholus** [devspace/devspace-user-requests#100]
Let me start off this bug report by thanking all of the devspace people for creating such a useful service, and for free no less! I use it every day and this sort of thing has been missing from the GitHub experience for a while. Very impressive work.

The notifications icon appeared a couple days ago. I believe this is a new feature. But often, the number of notifications indicated on the icon is stale. For example, if I click on the icon, read my notifications, and go back into devspace, the count remains the same (for quite a while, seemingly hours or even more).

**Comment by zenorocha** [comment]
Hey @rnicholus! The entire DevSpace team (only me for now :P) appreciates your comment. I'm SUPER happy to know that this is being useful for you.

You're right about the bug, I noticed that the browser was caching the request, that's why it didn't update.

I just pushed a fix so try now and let me know what you think (remember to clear your service workers cache).

**Comment by rnicholus** [comment]
Seems to be fixed! Thanks for the quick response.

**Comment by zenorocha** [comment]
Awesome ;D
