### ISSUE TITLE
List with Mentions

### ISSUE THREAD

**Issue by andrenatal** [devspace/devspace-user-requests#96]
I'd like to have a column with every mention of my github handle.

**Comment by zenorocha** [comment]
Hey @andrenatal, sorry for taking so reply. For now DevSpace only uses the Activities API for columns, that means we don't have access to this kind of information. But since [v1.0.0-beta.7](https://github.com/devspace/devspace/releases/tag/v1.0.0-beta.7) we added the Notifications icon which shows a counter for exactly what you want. In the future, we plan to have a whole UI dedicated to Notifications.
